### ISSUE TITLE
Dear chieund, I can't create the database table

### ISSUE THREAD

**Issue by StarDxxx** [chieund/crawl#88]
Dear chieund:
         I can't create the database tables. It need tags, articles and other tables.
         Can you share the table struction of this table? Thanks for your help!

![image](https://user-images.githubusercontent.com/36352922/188293597-ad467222-7999-44c0-a6e1-a54d250480a1.png)

**Comment by chieund** [comment]
@StarDxxx Dear StarDxxx
database you used it old. so i updated new database full table in PR
https://github.com/chieund/crawl/pull/89/files

you rebuild docker local

**Comment by StarDxxx** [comment]
Thanks for your help! you are very nice!
